In [33]:
import numpy as np

x = np.arange(20.0).reshape(4, 5)
x

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

Get first column

In [28]:
x[:,0]

array([ 0.,  5., 10., 15.])

Get first row

In [29]:
x[0,:]

array([0., 1., 2., 3., 4.])

Get everything besides the first column

In [30]:
x[:,1:5]

array([[ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.],
       [11., 12., 13., 14.],
       [16., 17., 18., 19.]])

Get everything besides the first columns without knowing the number of columns

In [32]:
row,col = x.shape

x[:,1:col]

array([[ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.],
       [11., 12., 13., 14.],
       [16., 17., 18., 19.]])